### ISSUE TITLE
here hold a crash in GLAllocation

### ISSUE THREAD

**Issue by asiekierka** [purpleposeidon/Factorization#13]
Did you deallocate a display list twice? I used Compression Crafters a bit then flew around an otherwise untouched, vanilla, pristine world.

[21:40:31] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 1/29/18 9:40 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.renderer.GLAllocation.func_74523_b(SourceFile:23)
	at factorization.weird.TileEntityDayBarrel.iterateForFinalizedBarrels(TileEntityDayBarrel.java:1136)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_61_TileEntityDayBarrel_iterateForFinalizedBarrels_ClientTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:330)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2064)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.GLAllocation.func_74523_b(SourceFile:23)
	at factorization.weird.TileEntityDayBarrel.iterateForFinalizedBarrels(TileEntityDayBarrel.java:1136)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_61_TileEntityDayBarrel_iterateForFinalizedBarrels_ClientTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:330)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['<PROFILE NAME>'/388, l='MpServer', x=249.14, y=74.73, z=252.13]]
	Chunk stats: MultiplayerChunkCache: 593, 593
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (252,64,248), Chunk: (at 12,4,8 in 15,15; contains blocks 240,0,240 to 255,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 5598 game time, 5598 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 101 total; [EntityBat['Bat'/8968, l='MpServer', x=263.07, y=35.88, z=176.63], EntitySkeleton['Skeleton'/9231, l='MpServer', x=240.44, y=59.00, z=207.84], EntityPig['Pig'/272, l='MpServer', x=317.50, y=66.00, z=182.50], EntityPig['Pig'/273, l='MpServer', x=315.19, y=67.00, z=181.16], EntityPig['Pig'/274, l='MpServer', x=318.50, y=65.00, z=182.50], EntityZombie['Zombie'/9234, l='MpServer', x=257.50, y=26.00, z=274.50], EntityMinecartChest['entity.MinecartChest.name'/275, l='MpServer', x=312.50, y=37.50, z=217.50], EntitySkeleton['Skeleton'/9235, l='MpServer', x=260.50, y=26.00, z=281.50], EntityItem['item.tile.gravel'/276, l='MpServer', x=313.47, y=37.13, z=228.59], EntitySkeleton['Skeleton'/9748, l='MpServer', x=198.50, y=37.00, z=267.09], EntitySkeleton['Skeleton'/9749, l='MpServer', x=194.44, y=36.00, z=261.50], EntityPig['Pig'/283, l='MpServer', x=320.50, y=64.00, z=181.50], EntityBat['Bat'/9767, l='MpServer', x=318.44, y=45.06, z=304.73], EntityBat['Bat'/9768, l='MpServer', x=320.47, y=49.10, z=294.31], EntityBat['Bat'/9770, l='MpServer', x=322.00, y=40.83, z=268.00], EntityBat['Bat'/9014, l='MpServer', x=312.00, y=20.00, z=258.53], EntityBat['Bat'/9015, l='MpServer', x=299.88, y=19.64, z=265.06], EntityBat['Bat'/9016, l='MpServer', x=295.06, y=18.00, z=266.50], EntityZombie['Zombie'/9275, l='MpServer', x=193.50, y=12.00, z=264.50], EntityCreeper['Creeper'/10300, l='MpServer', x=263.50, y=16.00, z=276.50], EntityCreeper['Creeper'/10301, l='MpServer', x=265.50, y=16.00, z=275.50], EntityZombie['Zombie'/7998, l='MpServer', x=252.50, y=31.00, z=231.50], EntitySkeleton['Skeleton'/8001, l='MpServer', x=253.50, y=31.00, z=231.50], EntitySkeleton['Skeleton'/9797, l='MpServer', x=195.50, y=45.00, z=299.50], EntityCreeper['Creeper'/10055, l='MpServer', x=328.50, y=37.00, z=237.50], EntityZombie['Zombie'/10056, l='MpServer', x=329.50, y=37.00, z=236.50], EntitySkeleton['Skeleton'/9547, l='MpServer', x=282.50, y=32.00, z=323.50], EntityCreeper['Creeper'/9548, l='MpServer', x=287.00, y=31.00, z=319.63], EntitySkeleton['Skeleton'/10060, l='MpServer', x=214.50, y=60.00, z=314.50], EntitySkeleton['Skeleton'/9042, l='MpServer', x=177.50, y=51.00, z=238.50], EntitySkeleton['Skeleton'/9558, l='MpServer', x=211.50, y=50.00, z=218.50], EntityCreeper['Creeper'/10332, l='MpServer', x=234.50, y=54.00, z=220.50], EntityZombie['Zombie'/7518, l='MpServer', x=181.50, y=36.00, z=194.50], EntityZombie['Zombie'/5476, l='MpServer', x=195.53, y=39.00, z=284.97], EntityChicken['Chicken'/107, l='MpServer', x=173.50, y=85.00, z=327.50], EntityChicken['Chicken'/109, l='MpServer', x=172.50, y=85.00, z=326.50], EntityZombie['Zombie'/9843, l='MpServer', x=174.50, y=12.00, z=255.50], EntityZombie['Zombie'/9844, l='MpServer', x=175.50, y=12.00, z=255.50], EntityCreeper['Creeper'/9845, l='MpServer', x=171.50, y=20.00, z=173.50], EntityZombie['Zombie'/9846, l='MpServer', x=171.50, y=20.00, z=171.50], EntityZombie['Zombie'/9341, l='MpServer', x=219.50, y=23.00, z=222.50], EntityClientPlayerMP['<PROFILE NAME>'/388, l='MpServer', x=249.14, y=74.73, z=252.13], EntityChicken['Chicken'/133, l='MpServer', x=204.53, y=71.00, z=267.41], EntityChicken['Chicken'/134, l='MpServer', x=205.53, y=71.00, z=266.38], EntityCreeper['Creeper'/9350, l='MpServer', x=174.13, y=63.00, z=265.25], EntityChicken['Chicken'/135, l='MpServer', x=205.53, y=71.00, z=268.41], EntityZombie['Zombie'/9098, l='MpServer', x=312.03, y=20.00, z=300.53], EntityCreeper['Creeper'/9099, l='MpServer', x=308.44, y=21.00, z=302.44], EntityCreeper['Creeper'/9104, l='MpServer', x=214.50, y=16.00, z=243.50], EntityBat['Bat'/6809, l='MpServer', x=241.44, y=29.10, z=257.75], EntityChicken['Chicken'/161, l='MpServer', x=217.50, y=70.00, z=223.50], EntityChicken['Chicken'/164, l='MpServer', x=216.50, y=70.00, z=224.50], EntityChicken['Chicken'/165, l='MpServer', x=217.59, y=70.00, z=228.66], EntityChicken['Chicken'/166, l='MpServer', x=212.56, y=70.00, z=230.47], EntityChicken['Chicken'/167, l='MpServer', x=210.50, y=71.00, z=260.50], EntityChicken['Chicken'/168, l='MpServer', x=223.50, y=69.00, z=302.50], EntitySpider['Spider'/9384, l='MpServer', x=327.50, y=38.00, z=259.50], EntityChicken['Chicken'/169, l='MpServer', x=216.56, y=69.00, z=303.53], EntitySpider['Spider'/7595, l='MpServer', x=308.44, y=38.00, z=294.75], EntityChicken['Chicken'/172, l='MpServer', x=216.50, y=69.00, z=323.50], EntityChicken['Chicken'/173, l='MpServer', x=216.50, y=69.00, z=323.50], EntityChicken['Chicken'/174, l='MpServer', x=216.50, y=69.00, z=325.50], EntityChicken['Chicken'/175, l='MpServer', x=217.47, y=69.00, z=319.56], EntityCreeper['Creeper'/6576, l='MpServer', x=229.50, y=61.00, z=313.50], EntitySkeleton['Skeleton'/8372, l='MpServer', x=249.91, y=32.00, z=234.50], EntityCreeper['Creeper'/8894, l='MpServer', x=295.50, y=22.00, z=253.50], EntityChicken['Chicken'/192, l='MpServer', x=224.50, y=69.00, z=302.50], EntityChicken['Chicken'/193, l='MpServer', x=229.41, y=69.00, z=298.63], EntityChicken['Chicken'/202, l='MpServer', x=261.44, y=69.00, z=211.56], EntityChicken['Chicken'/203, l='MpServer', x=251.53, y=67.00, z=299.47], EntityChicken['Chicken'/204, l='MpServer', x=259.53, y=71.00, z=312.63], EntityChicken['Chicken'/212, l='MpServer', x=247.47, y=69.00, z=217.56], EntityChicken['Chicken'/213, l='MpServer', x=274.38, y=71.00, z=225.47], EntityChicken['Chicken'/214, l='MpServer', x=280.59, y=71.00, z=260.91], EntityChicken['Chicken'/216, l='MpServer', x=286.44, y=70.00, z=245.56], EntitySkeleton['Skeleton'/9944, l='MpServer', x=193.39, y=16.00, z=196.46], EntityChicken['Chicken'/217, l='MpServer', x=245.53, y=70.00, z=242.53], EntityChicken['Chicken'/218, l='MpServer', x=253.44, y=70.00, z=258.63], EntityZombie['Zombie'/7642, l='MpServer', x=272.50, y=21.00, z=243.50], EntityChicken['Chicken'/219, l='MpServer', x=263.47, y=70.00, z=262.47], EntityChicken['Chicken'/220, l='MpServer', x=256.88, y=71.00, z=298.03], EntityChicken['Chicken'/221, l='MpServer', x=262.50, y=72.00, z=296.50], EntityChicken['Chicken'/222, l='MpServer', x=267.44, y=72.00, z=295.53], EntityChicken['Chicken'/223, l='MpServer', x=268.63, y=66.00, z=317.34], EntityChicken['Chicken'/224, l='MpServer', x=268.50, y=64.00, z=318.50], EntityChicken['Chicken'/225, l='MpServer', x=268.50, y=64.00, z=318.50], EntitySkeleton['Skeleton'/5601, l='MpServer', x=196.50, y=36.00, z=254.50], EntityChicken['Chicken'/229, l='MpServer', x=260.50, y=63.00, z=321.50], EntityChicken['Chicken'/230, l='MpServer', x=260.50, y=63.00, z=322.50], EntityBat['Bat'/5350, l='MpServer', x=176.54, y=48.85, z=315.75], EntityChicken['Chicken'/231, l='MpServer', x=259.50, y=63.00, z=323.50], EntityChicken['Chicken'/232, l='MpServer', x=264.53, y=62.35, z=326.53], EntityZombie['Zombie'/8690, l='MpServer', x=186.50, y=14.00, z=257.50], EntityChicken['Chicken'/243, l='MpServer', x=280.44, y=67.00, z=296.97], EntitySkeleton['Skeleton'/8435, l='MpServer', x=195.50, y=46.00, z=301.50], EntityChicken['Chicken'/244, l='MpServer', x=286.50, y=64.00, z=292.50], EntitySkeleton['Skeleton'/8436, l='MpServer', x=195.13, y=44.00, z=298.47], EntityChicken['Chicken'/245, l='MpServer', x=283.50, y=65.00, z=293.50], EntityChicken['Chicken'/246, l='MpServer', x=276.59, y=67.00, z=300.41], EntityZombie['Zombie'/6904, l='MpServer', x=313.50, y=25.00, z=277.50], EntityZombie['Zombie'/9720, l='MpServer', x=190.50, y=36.00, z=266.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 4.14.15_2
	Java Version: 1.8.0_182, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3312835240 bytes (3159 MB) / 4172283904 bytes (3979 MB) up to 4172283904 bytes (3979 MB)
	JVM Flags: 2 total; -Xms4096m -Xmx4096m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHIJAAAA	factorization.notify{1.0} [Factorization Notification System] (Factorization-1.7.10-0.8.108.jar) 
	UCHIJAAAA	factorization.dimensionalSlice{0.8.108} [Factorization Dimensional Slices] (Factorization-1.7.10-0.8.108.jar) 
	UCHIJAAAA	factorization{0.8.108} [Factorization] (Factorization-1.7.10-0.8.108.jar) 
	UCHIJAAAA	factorization.misc{0.8.108} [Factorization Miscellaneous Nonsense] (Factorization-1.7.10-0.8.108.jar) 
	UCHIJAAAA	fz.scrap{0.8.108} [Scrap] (Factorization-1.7.10-0.8.108.jar) 
	UCHIJAAAA	factorization.truth{0.8.108} [Truth] (Factorization-1.7.10-0.8.108.jar) 
	GL info: ' Vendor: 'Intel Open Source Technology Center' Version: '3.0 Mesa 17.3.3' Renderer: 'Mesa DRI Intel(R) Haswell Desktop '
	Launched Version: MultiMC5
	LWJGL: 2.9.1
	OpenGL: Mesa DRI Intel(R) Haswell Desktop  GL version 3.0 Mesa 17.3.3, Intel Open Source Technology Center
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
[21:40:31] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:359]: #@!@# Game crashed! Crash report saved to: #@!@# /home/asie/.multimc/instances/1.7.10_test/minecraft/crash-reports/crash-2018-01-29_21.40.31-client.txt

**Comment by asiekierka** [comment]
https://github.com/purpleposeidon/Factorization/commit/c161e065f7ed93b1785d5d2fd40bc07831b2a964

**Comment by asiekierka** [comment]
From my tests, this fixes it.
