### ISSUE TITLE
[CRASH] Upon load, error after main menu with settings

### ISSUE THREAD

**Issue by ranger135xp** [purpleposeidon/Factorization#9]
I got this error while the game was sitting at the main menu. It crashed shortly after loading.

`java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.settings.GameSettings.func_82879_c(GameSettings.java:1157)
	at net.minecraft.client.settings.GameSettings.func_74303_b(GameSettings.java:1139)
	at factorization.misc.MiscClientCommands$miscCommands.savesettings(MiscClientCommands.java:204)
	at factorization.misc.MiscClientTickHandler.setupPickBlockKey(MiscClientTickHandler.java:191)
	at factorization.misc.MiscClientTickHandler.emitLoadAlert(MiscClientTickHandler.java:56)
	at factorization.misc.MiscClientTickHandler.clientTicks(MiscClientTickHandler.java:37)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1428_MiscClientTickHandler_clientTicks_ClientTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:325)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1587)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

EDIT:\ I found the issue to be that FZ does not like its pick block to be set to nothing. I switched back to the default MC pick block because of the incompatibility with AE2 but this now causes my client to crash if it is not configured. I'll try just giving it a crap key instead.

**Comment by ranger135xp** [comment]
I can confirm that Pick Block (FZ) must be set to anything other than NONE or MC crashes the next time it is started while at the main menu.

**Comment by asiekierka** [comment]
(Or you could have just set FZ's config option to false.)
